name: motion_hack
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.9
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  get: 4.6.6
  introduction_screen: ^3.1.14

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile/
    - assets/images/background/
    - assets/images/items/
    - assets/images/icons/